version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "xray-consumer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17jscamjeut1t"
s3_prefix = "xray-consumer"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
